name: PRcop

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
      - review_request_removed
      - pull_request_review_comment
  pull_request_review_comment:
    types:
      - created
      - deleted

jobs:
  prcop:
    runs-on: ubuntu-latest
    name: PRcop
    steps:
      - name: Linting Pull Request
        uses: makaroni4/prcop@v1.0.14
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          description-min-words: 20
          min-comments: 1
          disable-word: prcop:disable
