name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Specs
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm test
